<?php

namespace LOUVRE\TicketBundle\Repository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{

    public function countVisitorsFor($datedevisite)
    {
        return (int) $this->createQueryBuilder('visiteurs')
            ->leftJoin('visiteurs.billet', 'billet')
            ->select('COUNT(visiteurs.id)')
            ->where('billet.datedevisite= :datedevisite')
            ->setParameter('datedevisite', $datedevisite)
            ->getQuery()
            ->getSingleScalarResult();
    }
    
}
